INSERT INTO facilities (name, dhis2id, dhis2_name)
    VALUES
    ('Arua RRH', 'THGKB3lHEUx', 'Arua Regional Referral Hospital'),
    ('Entebbe RRH', 'yApOnywci25', 'Entebbe Regional Referral Hospital'),
    ('Fort Portal RRH', 'Dt6WipQhr4Q', 'Fort Portal Regional Referral Hospital'),
    ('Gulu RRH', 'QDc7Wijvfca', 'Gulu Regional Referral Hospital'),
    ('Hoima RRH', 'V2ylFCAVj0U', 'Hoima Regional Referral Hospital'),
    ('Jinja RRH', 'SZS6IdnTKZR', 'Jinja Regional Referral Hospital'),
    ('Kabale RRH', 'K2BGHpaUluP', 'Kabale Regional Referral Hospital'),
    ('Lira RRH', 'cK5namCwmbW', 'Lira Regional Referral Hospital'),
    ('Masaka', 'vX6kcAwvaS0', 'Masaka Regional Referral Hospital'),
    ('Mbale RRH', 'HpJYuf9iyz2', 'Mbale Regional Referral Hospital'),
    ('Mbarara RRH', 'ZpJgSAyZtkl', 'Mbarara Regional Referral Hospital'),
    ('Moroto RRH', 'cK0jOJzBIvd', 'Moroto Regional Referral Hospital'),
    ('Mubende RRH', 'VLclxVcJh5v', 'Mubende Regional Referral Hospital'),
    ('Soroti RRH', 'Nnms2rd2gpC', 'Soroti Regional Referral Hospital');

INSERT INTO organisms (name, code, in_dhis2, dhis2_order) 
VALUES
('Klebsiella Pneumoniae', 'kpn', TRUE, 0),
('Escherichia Coli', 'eco', TRUE, 1),
('Salmonella spp', 'sal', TRUE, 2),
('Shigella spp', 'shi', TRUE, 3),
('Neisseria Gonorrhoeae', 'ngo', TRUE, 4),
('Staphylococcus Aureus', 'sau', TRUE, 5),
('Streptococcus Pneumoniae', 'spn', TRUE, 6),
('Acinetobacter Baumannii', 'aba', TRUE, 7),
('Vibrio Cholerae', 'vic', TRUE, 8),
('Enterococcus spp', 'ent', TRUE, 9),
('Haemophilus Influenzae', 'hin', TRUE, 10),
('Neisseria Meningitidis', 'nme', TRUE, 11),
('Candida Albicans', 'cal', FALSE, 0);

INSERT INTO antibiotics (name, code, disis_code, in_dhis2, dhis2_order)
VALUES
('Ampicilin', 'amp', 'AMP_ND10', TRUE, 0),
('Azithromycin', 'azm', 'AZM_ND15', TRUE, 1),
('Amikacin', 'amk', 'AMK_ND30', TRUE, 2),
('Ceftriaxone', 'cro', 'CRO_ND30', TRUE, 3),
('Ceftazidime', 'caz', 'CAZ_ND30', TRUE, 4),
('Cefotaxime', 'ctx', 'CTX_ND30', TRUE, 5),
('Cefoxitin', 'fox', 'FOX_ND30', TRUE, 6),
('Cefixime', 'cfm', 'CFM_ND5', TRUE, 7),
('Ciprofloxacin', 'cip', 'CIP_ND5', TRUE, 8),
('Colistin', 'col', 'COL_ND10', TRUE, 9),
('Gentamicin', 'gen', 'GEN_ND10', TRUE, 10),
('Imipenem', 'ipm', 'IPM_ND10', TRUE, 11),
('Levofloxacin', 'lvx', 'LVX_ND5', TRUE, 12),
('Meropenem', 'mem', 'MEM_ND10', TRUE, 13),
('Oxacillin', 'oxa', 'OXA_ND1', TRUE, 14),
('Penicillin G', 'pen', 'PEN_ND10', TRUE, 15),
('Vancomycin', 'van', 'VAN_ND30', TRUE, 16),
('Chloramphenicol', 'chl', 'CHL_ND30', TRUE, 17),
('Clindamycin', 'cli', 'CLI_ND2', TRUE, 18),
('Erythromycin', 'ery', 'ERY_ND15', TRUE, 19),
('Nalidixic acid', 'nal', 'NAL_ND30', TRUE, 20),
('Nitrofurantoin', 'nit', 'NIT_ND300', TRUE, 21),
('Piperacillin', 'pip', 'PIP_ND100', TRUE, 22),
('Tetracycline', 'tcy', 'TCY_ND30', TRUE, 23),
('Tobramycin', 'tob', 'TOB_ND10', FALSE, 0);

INSERT INTO indicator_mapping (form, slug, cmd, form_order, description, dataset, dataelement, category_option_combo)
VALUES
('iso', 'iso_kpn', 'kpn', 0, 'Klebsiella pneumoniae isolates', 'quMWqLxzcfO', 'qOIzKee6FfH', 'm5hErsQLQuW' ),
('iso', 'iso_eco', 'eco', 1, 'Escherichia coli', 'quMWqLxzcfO', 'qOIzKee6FfH', 'EOYkrLSx21s' ),
('iso', 'iso_sal', 'sal', 2, 'Salmonella spp isolates', 'quMWqLxzcfO', 'qOIzKee6FfH', 'UqbCWSg5rOu' ),
('iso', 'iso_shi', 'shi', 3, 'Shigella spp isolates', 'quMWqLxzcfO', 'qOIzKee6FfH', 'UorkSGAPM8h' ),
('iso', 'iso_ngo', 'ngo', 4, 'Neisseria Gonorrhoeae isolates', 'quMWqLxzcfO', 'qOIzKee6FfH', 'g3B2DuwQTWP' ),
('iso', 'iso_sau', 'sau', 5, 'Staphylococcus Aureus isolates', 'quMWqLxzcfO', 'qOIzKee6FfH', 'DyV5gINiVaz' ),
('iso', 'iso_spn', 'spn', 6, 'Streptococcus Pneumoniae isolates', 'quMWqLxzcfO', 'qOIzKee6FfH', 'oeuHrQ5EEJ0' ),
('iso', 'iso_aba', 'aba', 7, 'Acinetobacter Baumannii isolates', 'quMWqLxzcfO', 'qOIzKee6FfH', 'sv84aXQFfYn' ),
('iso', 'iso_vic', 'vic', 8, 'Vibrio cholerae', 'quMWqLxzcfO', 'qOIzKee6FfH', 'lE1dfuSi7wH'),
('iso', 'iso_ent', 'ent', 9, 'Enterococcus spp isolates', 'quMWqLxzcfO', 'qOIzKee6FfH', 'PgTYXkpS7iQ' ),
('iso', 'iso_hin', 'hin', 10, 'Haemophilus Influenzae isolates', 'quMWqLxzcfO', 'qOIzKee6FfH', 'OCKc2GVWRnR' ),
('iso', 'iso_nme', 'nme', 11, 'Neisseria Meningitidis', 'quMWqLxzcfO', 'qOIzKee6FfH', 'JwizPqF3Co8' ),

/* Ampicilin */
('amp', 'amp_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'X9MHIf0Wm6y'),
('amp', 'amp_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'WeHrikdo7oo'),
('amp', 'amp_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'hPnuIjnYi9C'),
('amp', 'amp_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'ZFaU7TaQRZp'),
('amp', 'amp_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'FbXf2g4uhos'),
('amp', 'amp_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'iCcPaU1SKnO'),
('amp', 'amp_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'eSNEiqOgZ03'),
('amp', 'amp_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'Jy5IeplgNcs'),
('amp', 'amp_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'VgMvVNtkUPv'),
('amp', 'amp_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'Fh2PZJLtV3U'),
('amp', 'amp_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'bOIEbuipQ0H'),
('amp', 'amp_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'p3TAhB2UZiS'),
('amp', 'amp_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'xvR3x8vLvRK'),
('amp', 'amp_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'efl41btBUk9'),
('amp', 'amp_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'ccisVG8SxHv'),
('amp', 'amp_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'ZG21E9j1Bod'),
('amp', 'amp_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'UdeU9gsKqI3'),
('amp', 'amp_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'DI0hjMRK5Zh'),
('amp', 'amp_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'ov2i9IayA9m'),
('amp', 'amp_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'qX0d8PnsJvA'),
('amp', 'amp_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'WkldENuMjt8'),
('amp', 'amp_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'z9OAlfoLrhF'),
('amp', 'amp_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'xhGDprZjJIy'),
('amp', 'amp_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'KMjCdte3nlv'),
('amp', 'amp_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'ameRGjO5AW3'),
('amp', 'amp_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'LncgC06sQdO'),
('amp', 'amp_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'LQQ8pGWtkiH'),
('amp', 'amp_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'UXnM8Pm6vP0'),
('amp', 'amp_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'ksXHrNHHHtY'),
('amp', 'amp_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'bfTAqApCiIb'),
('amp', 'amp_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'nm7Wxy7HTuy'),
('amp', 'amp_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'o9EG0vv4RnO'),
('amp', 'amp_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'rZLHuzg0Ayi'),
('amp', 'amp_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'KrzsPmVyImR'),
('amp', 'amp_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'Xyw52ZcXySb'),
('amp', 'amp_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'O7gTvu2U4l1', 'rkY5vfbP0SS'),

/* Azithromycin */
/* ('azm', 'azm_', '', 0, '', 'quMWqLxzcfO', '', '' ),*/
('azm', 'azm_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'X9MHIf0Wm6y'),
('azm', 'azm_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'WeHrikdo7oo'),
('azm', 'azm_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'hPnuIjnYi9C'),
('azm', 'azm_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'ZFaU7TaQRZp'),
('azm', 'azm_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'FbXf2g4uhos'),
('azm', 'azm_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'iCcPaU1SKnO'),
('azm', 'azm_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'eSNEiqOgZ03'),
('azm', 'azm_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'Jy5IeplgNcs'),
('azm', 'azm_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'VgMvVNtkUPv'),
('azm', 'azm_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'Fh2PZJLtV3U'),
('azm', 'azm_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'bOIEbuipQ0H'),
('azm', 'azm_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'p3TAhB2UZiS'),
('azm', 'azm_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'xvR3x8vLvRK'),
('azm', 'azm_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'efl41btBUk9'),
('azm', 'azm_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'ccisVG8SxHv'),
('azm', 'azm_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'ZG21E9j1Bod'),
('azm', 'azm_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'UdeU9gsKqI3'),
('azm', 'azm_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'DI0hjMRK5Zh'),
('azm', 'azm_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'ov2i9IayA9m'),
('azm', 'azm_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'qX0d8PnsJvA'),
('azm', 'azm_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'WkldENuMjt8'),
('azm', 'azm_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'z9OAlfoLrhF'),
('azm', 'azm_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'xhGDprZjJIy'),
('azm', 'azm_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'KMjCdte3nlv'),
('azm', 'azm_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'ameRGjO5AW3'),
('azm', 'azm_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'LncgC06sQdO'),
('azm', 'azm_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'LQQ8pGWtkiH'),
('azm', 'azm_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'UXnM8Pm6vP0'),
('azm', 'azm_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'ksXHrNHHHtY'),
('azm', 'azm_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'bfTAqApCiIb'),
('azm', 'azm_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'nm7Wxy7HTuy'),
('azm', 'azm_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'o9EG0vv4RnO'),
('azm', 'azm_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'rZLHuzg0Ayi'),
('azm', 'azm_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'KrzsPmVyImR'),
('azm', 'azm_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'Xyw52ZcXySb'),
('azm', 'azm_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'VPeyoFOWNlf', 'rkY5vfbP0SS'),

/* Amikacin */
/*('amk', 'amk_', '', 0, '', 'quMWqLxzcfO', '', '' ),*/
('amk', 'amk_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'X9MHIf0Wm6y'),
('amk', 'amk_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'WeHrikdo7oo'),
('amk', 'amk_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'hPnuIjnYi9C'),
('amk', 'amk_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'ZFaU7TaQRZp'),
('amk', 'amk_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'FbXf2g4uhos'),
('amk', 'amk_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'iCcPaU1SKnO'),
('amk', 'amk_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'eSNEiqOgZ03'),
('amk', 'amk_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'Jy5IeplgNcs'),
('amk', 'amk_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'VgMvVNtkUPv'),
('amk', 'amk_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'Fh2PZJLtV3U'),
('amk', 'amk_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'bOIEbuipQ0H'),
('amk', 'amk_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'p3TAhB2UZiS'),
('amk', 'amk_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'xvR3x8vLvRK'),
('amk', 'amk_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'efl41btBUk9'),
('amk', 'amk_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'ccisVG8SxHv'),
('amk', 'amk_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'ZG21E9j1Bod'),
('amk', 'amk_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'UdeU9gsKqI3'),
('amk', 'amk_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'DI0hjMRK5Zh'),
('amk', 'amk_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'ov2i9IayA9m'),
('amk', 'amk_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'qX0d8PnsJvA'),
('amk', 'amk_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'WkldENuMjt8'),
('amk', 'amk_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'z9OAlfoLrhF'),
('amk', 'amk_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'xhGDprZjJIy'),
('amk', 'amk_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'KMjCdte3nlv'),
('amk', 'amk_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'ameRGjO5AW3'),
('amk', 'amk_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'LncgC06sQdO'),
('amk', 'amk_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'LQQ8pGWtkiH'),
('amk', 'amk_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'UXnM8Pm6vP0'),
('amk', 'amk_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'ksXHrNHHHtY'),
('amk', 'amk_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'bfTAqApCiIb'),
('amk', 'amk_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'nm7Wxy7HTuy'),
('amk', 'amk_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'o9EG0vv4RnO'),
('amk', 'amk_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'rZLHuzg0Ayi'),
('amk', 'amk_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'KrzsPmVyImR'),
('amk', 'amk_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'Xyw52ZcXySb'),
('amk', 'amk_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'JhpEqt6FvBn', 'rkY5vfbP0SS'),

/* Ceftriaxone - cro */
('cro', 'cro_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'CqXFeqgb491', 'X9MHIf0Wm6y' ),
('cro', 'cro_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'CqXFeqgb491', 'WeHrikdo7oo' ),
('cro', 'cro_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'CqXFeqgb491', 'hPnuIjnYi9C' ),
('cro', 'cro_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'CqXFeqgb491', 'ZFaU7TaQRZp' ),
('cro', 'cro_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'CqXFeqgb491', 'FbXf2g4uhos' ),
('cro', 'cro_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'CqXFeqgb491', 'iCcPaU1SKnO' ),
('cro', 'cro_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'CqXFeqgb491', 'eSNEiqOgZ03' ),
('cro', 'cro_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'CqXFeqgb491', 'Jy5IeplgNcs' ),
('cro', 'cro_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'CqXFeqgb491', 'VgMvVNtkUPv' ),
('cro', 'cro_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'CqXFeqgb491', 'Fh2PZJLtV3U' ),
('cro', 'cro_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'bOIEbuipQ0H' ),
('cro', 'cro_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'p3TAhB2UZiS' ),
('cro', 'cro_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'xvR3x8vLvRK' ),
('cro', 'cro_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'efl41btBUk9' ),
('cro', 'cro_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'ccisVG8SxHv' ),
('cro', 'cro_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'ZG21E9j1Bod' ),
('cro', 'cro_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'UdeU9gsKqI3' ),
('cro', 'cro_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'DI0hjMRK5Zh' ),
('cro', 'cro_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'ov2i9IayA9m' ),
('cro', 'cro_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'qX0d8PnsJvA' ),
('cro', 'cro_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'WkldENuMjt8' ),
('cro', 'cro_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'z9OAlfoLrhF' ),
('cro', 'cro_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'xhGDprZjJIy' ),
('cro', 'cro_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'KMjCdte3nlv' ),
('cro', 'cro_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'ameRGjO5AW3' ),
('cro', 'cro_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'LncgC06sQdO' ),
('cro', 'cro_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'LQQ8pGWtkiH' ),
('cro', 'cro_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'UXnM8Pm6vP0' ),
('cro', 'cro_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'ksXHrNHHHtY' ),
('cro', 'cro_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'bfTAqApCiIb' ),
('cro', 'cro_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'nm7Wxy7HTuy' ),
('cro', 'cro_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'o9EG0vv4RnO' ),
('cro', 'cro_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'rZLHuzg0Ayi' ),
('cro', 'cro_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'KrzsPmVyImR' ),
('cro', 'cro_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'Xyw52ZcXySb' ),
('cro', 'cro_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'CqXFeqgb491', 'rkY5vfbP0SS' ),

/* Ceftazidime - caz */
('caz', 'caz_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'X9MHIf0Wm6y' ),
('caz', 'caz_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'WeHrikdo7oo' ),
('caz', 'caz_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'hPnuIjnYi9C' ),
('caz', 'caz_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'ZFaU7TaQRZp' ),
('caz', 'caz_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'FbXf2g4uhos' ),
('caz', 'caz_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'iCcPaU1SKnO' ),
('caz', 'caz_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'eSNEiqOgZ03' ),
('caz', 'caz_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'Jy5IeplgNcs' ),
('caz', 'caz_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'VgMvVNtkUPv' ),
('caz', 'caz_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'Fh2PZJLtV3U' ),
('caz', 'caz_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'bOIEbuipQ0H' ),
('caz', 'caz_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'p3TAhB2UZiS' ),
('caz', 'caz_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'xvR3x8vLvRK' ),
('caz', 'caz_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'efl41btBUk9' ),
('caz', 'caz_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'ccisVG8SxHv' ),
('caz', 'caz_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'ZG21E9j1Bod' ),
('caz', 'caz_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'UdeU9gsKqI3' ),
('caz', 'caz_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'DI0hjMRK5Zh' ),
('caz', 'caz_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'ov2i9IayA9m' ),
('caz', 'caz_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'qX0d8PnsJvA' ),
('caz', 'caz_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'WkldENuMjt8' ),
('caz', 'caz_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'z9OAlfoLrhF' ),
('caz', 'caz_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'xhGDprZjJIy' ),
('caz', 'caz_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'KMjCdte3nlv' ),
('caz', 'caz_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'ameRGjO5AW3' ),
('caz', 'caz_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'LncgC06sQdO' ),
('caz', 'caz_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'LQQ8pGWtkiH' ),
('caz', 'caz_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'UXnM8Pm6vP0' ),
('caz', 'caz_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'ksXHrNHHHtY' ),
('caz', 'caz_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'bfTAqApCiIb' ),
('caz', 'caz_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'nm7Wxy7HTuy' ),
('caz', 'caz_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'o9EG0vv4RnO' ),
('caz', 'caz_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'rZLHuzg0Ayi' ),
('caz', 'caz_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'KrzsPmVyImR' ),
('caz', 'caz_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'Xyw52ZcXySb' ),
('caz', 'caz_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'AOjHKsS7vyM', 'rkY5vfbP0SS' ),
/* Cefotaxime - ctx */
('ctx', 'ctx_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'oCECgzam7Us', 'X9MHIf0Wm6y' ),
('ctx', 'ctx_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'oCECgzam7Us', 'WeHrikdo7oo' ),
('ctx', 'ctx_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'oCECgzam7Us', 'hPnuIjnYi9C' ),
('ctx', 'ctx_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'oCECgzam7Us', 'ZFaU7TaQRZp' ),
('ctx', 'ctx_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'oCECgzam7Us', 'FbXf2g4uhos' ),
('ctx', 'ctx_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'oCECgzam7Us', 'iCcPaU1SKnO' ),
('ctx', 'ctx_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'oCECgzam7Us', 'eSNEiqOgZ03' ),
('ctx', 'ctx_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'oCECgzam7Us', 'Jy5IeplgNcs' ),
('ctx', 'ctx_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'oCECgzam7Us', 'VgMvVNtkUPv' ),
('ctx', 'ctx_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'oCECgzam7Us', 'Fh2PZJLtV3U' ),
('ctx', 'ctx_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'bOIEbuipQ0H' ),
('ctx', 'ctx_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'p3TAhB2UZiS' ),
('ctx', 'ctx_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'xvR3x8vLvRK' ),
('ctx', 'ctx_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'efl41btBUk9' ),
('ctx', 'ctx_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'ccisVG8SxHv' ),
('ctx', 'ctx_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'ZG21E9j1Bod' ),
('ctx', 'ctx_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'UdeU9gsKqI3' ),
('ctx', 'ctx_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'DI0hjMRK5Zh' ),
('ctx', 'ctx_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'ov2i9IayA9m' ),
('ctx', 'ctx_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'qX0d8PnsJvA' ),
('ctx', 'ctx_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'WkldENuMjt8' ),
('ctx', 'ctx_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'z9OAlfoLrhF' ),
('ctx', 'ctx_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'xhGDprZjJIy' ),
('ctx', 'ctx_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'KMjCdte3nlv' ),
('ctx', 'ctx_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'ameRGjO5AW3' ),
('ctx', 'ctx_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'LncgC06sQdO' ),
('ctx', 'ctx_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'LQQ8pGWtkiH' ),
('ctx', 'ctx_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'UXnM8Pm6vP0' ),
('ctx', 'ctx_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'ksXHrNHHHtY' ),
('ctx', 'ctx_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'bfTAqApCiIb' ),
('ctx', 'ctx_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'nm7Wxy7HTuy' ),
('ctx', 'ctx_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'o9EG0vv4RnO' ),
('ctx', 'ctx_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'rZLHuzg0Ayi' ),
('ctx', 'ctx_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'KrzsPmVyImR' ),
('ctx', 'ctx_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'Xyw52ZcXySb' ),
('ctx', 'ctx_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'oCECgzam7Us', 'rkY5vfbP0SS' ),

/* Cefoxitin - fox */
('fox', 'fox_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'X9MHIf0Wm6y' ),
('fox', 'fox_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'WeHrikdo7oo' ),
('fox', 'fox_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'hPnuIjnYi9C' ),
('fox', 'fox_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'ZFaU7TaQRZp' ),
('fox', 'fox_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'FbXf2g4uhos' ),
('fox', 'fox_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'iCcPaU1SKnO' ),
('fox', 'fox_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'eSNEiqOgZ03' ),
('fox', 'fox_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'Jy5IeplgNcs' ),
('fox', 'fox_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'VgMvVNtkUPv' ),
('fox', 'fox_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'Fh2PZJLtV3U' ),
('fox', 'fox_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'bOIEbuipQ0H' ),
('fox', 'fox_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'p3TAhB2UZiS' ),
('fox', 'fox_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'xvR3x8vLvRK' ),
('fox', 'fox_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'efl41btBUk9' ),
('fox', 'fox_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'ccisVG8SxHv' ),
('fox', 'fox_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'ZG21E9j1Bod' ),
('fox', 'fox_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'UdeU9gsKqI3' ),
('fox', 'fox_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'DI0hjMRK5Zh' ),
('fox', 'fox_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'ov2i9IayA9m' ),
('fox', 'fox_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'qX0d8PnsJvA' ),
('fox', 'fox_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'WkldENuMjt8' ),
('fox', 'fox_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'z9OAlfoLrhF' ),
('fox', 'fox_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'xhGDprZjJIy' ),
('fox', 'fox_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'KMjCdte3nlv' ),
('fox', 'fox_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'ameRGjO5AW3' ),
('fox', 'fox_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'LncgC06sQdO' ),
('fox', 'fox_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'LQQ8pGWtkiH' ),
('fox', 'fox_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'UXnM8Pm6vP0' ),
('fox', 'fox_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'ksXHrNHHHtY' ),
('fox', 'fox_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'bfTAqApCiIb' ),
('fox', 'fox_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'nm7Wxy7HTuy' ),
('fox', 'fox_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'o9EG0vv4RnO' ),
('fox', 'fox_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'rZLHuzg0Ayi' ),
('fox', 'fox_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'KrzsPmVyImR' ),
('fox', 'fox_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'Xyw52ZcXySb' ),
('fox', 'fox_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'yHqjB7fuSBv', 'rkY5vfbP0SS' ),

/* Cefixime - cfm */
('cfm', 'cfm_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'X9MHIf0Wm6y' ),
('cfm', 'cfm_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'WeHrikdo7oo' ),
('cfm', 'cfm_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'hPnuIjnYi9C' ),
('cfm', 'cfm_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'ZFaU7TaQRZp' ),
('cfm', 'cfm_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'FbXf2g4uhos' ),
('cfm', 'cfm_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'iCcPaU1SKnO' ),
('cfm', 'cfm_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'eSNEiqOgZ03' ),
('cfm', 'cfm_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'Jy5IeplgNcs' ),
('cfm', 'cfm_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'VgMvVNtkUPv' ),
('cfm', 'cfm_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'Fh2PZJLtV3U' ),
('cfm', 'cfm_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'bOIEbuipQ0H' ),
('cfm', 'cfm_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'p3TAhB2UZiS' ),
('cfm', 'cfm_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'xvR3x8vLvRK' ),
('cfm', 'cfm_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'efl41btBUk9' ),
('cfm', 'cfm_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'ccisVG8SxHv' ),
('cfm', 'cfm_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'ZG21E9j1Bod' ),
('cfm', 'cfm_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'UdeU9gsKqI3' ),
('cfm', 'cfm_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'DI0hjMRK5Zh' ),
('cfm', 'cfm_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'ov2i9IayA9m' ),
('cfm', 'cfm_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'qX0d8PnsJvA' ),
('cfm', 'cfm_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'WkldENuMjt8' ),
('cfm', 'cfm_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'z9OAlfoLrhF' ),
('cfm', 'cfm_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'xhGDprZjJIy' ),
('cfm', 'cfm_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'KMjCdte3nlv' ),
('cfm', 'cfm_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'ameRGjO5AW3' ),
('cfm', 'cfm_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'LncgC06sQdO' ),
('cfm', 'cfm_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'LQQ8pGWtkiH' ),
('cfm', 'cfm_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'UXnM8Pm6vP0' ),
('cfm', 'cfm_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'ksXHrNHHHtY' ),
('cfm', 'cfm_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'bfTAqApCiIb' ),
('cfm', 'cfm_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'nm7Wxy7HTuy' ),
('cfm', 'cfm_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'o9EG0vv4RnO' ),
('cfm', 'cfm_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'rZLHuzg0Ayi' ),
('cfm', 'cfm_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'KrzsPmVyImR' ),
('cfm', 'cfm_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'Xyw52ZcXySb' ),
('cfm', 'cfm_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'ACShbHTUYpt', 'rkY5vfbP0SS' ),

/* Cotrimoxazole */
/*
('', '', 'kpn_r', 0, '', 'quMWqLxzcfO', '', '' ),
('', '', 'kpn_i', 0, '', 'quMWqLxzcfO', '', '' ),
('', '', 'kpn_s', 0, '', 'quMWqLxzcfO', '', '' ),*/

/* Ciprofloxacin - cip */
('cip', 'cip_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'X9MHIf0Wm6y' ),
('cip', 'cip_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'WeHrikdo7oo' ),
('cip', 'cip_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'hPnuIjnYi9C' ),
('cip', 'cip_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'ZFaU7TaQRZp' ),
('cip', 'cip_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'FbXf2g4uhos' ),
('cip', 'cip_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'iCcPaU1SKnO' ),
('cip', 'cip_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'eSNEiqOgZ03' ),
('cip', 'cip_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'Jy5IeplgNcs' ),
('cip', 'cip_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'VgMvVNtkUPv' ),
('cip', 'cip_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'Fh2PZJLtV3U' ),
('cip', 'cip_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'bOIEbuipQ0H' ),
('cip', 'cip_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'p3TAhB2UZiS' ),
('cip', 'cip_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'xvR3x8vLvRK' ),
('cip', 'cip_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'efl41btBUk9' ),
('cip', 'cip_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'ccisVG8SxHv' ),
('cip', 'cip_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'ZG21E9j1Bod' ),
('cip', 'cip_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'UdeU9gsKqI3' ),
('cip', 'cip_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'DI0hjMRK5Zh' ),
('cip', 'cip_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'ov2i9IayA9m' ),
('cip', 'cip_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'qX0d8PnsJvA' ),
('cip', 'cip_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'WkldENuMjt8' ),
('cip', 'cip_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'z9OAlfoLrhF' ),
('cip', 'cip_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'xhGDprZjJIy' ),
('cip', 'cip_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'KMjCdte3nlv' ),
('cip', 'cip_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'ameRGjO5AW3' ),
('cip', 'cip_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'LncgC06sQdO' ),
('cip', 'cip_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'LQQ8pGWtkiH' ),
('cip', 'cip_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'UXnM8Pm6vP0' ),
('cip', 'cip_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'ksXHrNHHHtY' ),
('cip', 'cip_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'bfTAqApCiIb' ),
('cip', 'cip_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'nm7Wxy7HTuy' ),
('cip', 'cip_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'o9EG0vv4RnO' ),
('cip', 'cip_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'rZLHuzg0Ayi' ),
('cip', 'cip_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'KrzsPmVyImR' ),
('cip', 'cip_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'Xyw52ZcXySb' ),
('cip', 'cip_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'sbA8zvsMWlv', 'rkY5vfbP0SS' ),

/* Colistin - col */
('col', 'col_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'X9MHIf0Wm6y' ),
('col', 'col_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'WeHrikdo7oo' ),
('col', 'col_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'hPnuIjnYi9C' ),
('col', 'col_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'ZFaU7TaQRZp' ),
('col', 'col_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'FbXf2g4uhos' ),
('col', 'col_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'iCcPaU1SKnO' ),
('col', 'col_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'eSNEiqOgZ03' ),
('col', 'col_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'Jy5IeplgNcs' ),
('col', 'col_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'VgMvVNtkUPv' ),
('col', 'col_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'Fh2PZJLtV3U' ),
('col', 'col_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'bOIEbuipQ0H' ),
('col', 'col_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'p3TAhB2UZiS' ),
('col', 'col_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'xvR3x8vLvRK' ),
('col', 'col_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'efl41btBUk9' ),
('col', 'col_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'ccisVG8SxHv' ),
('col', 'col_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'ZG21E9j1Bod' ),
('col', 'col_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'UdeU9gsKqI3' ),
('col', 'col_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'DI0hjMRK5Zh' ),
('col', 'col_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'ov2i9IayA9m' ),
('col', 'col_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'qX0d8PnsJvA' ),
('col', 'col_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'WkldENuMjt8' ),
('col', 'col_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'z9OAlfoLrhF' ),
('col', 'col_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'xhGDprZjJIy' ),
('col', 'col_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'KMjCdte3nlv' ),
('col', 'col_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'ameRGjO5AW3' ),
('col', 'col_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'LncgC06sQdO' ),
('col', 'col_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'LQQ8pGWtkiH' ),
('col', 'col_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'UXnM8Pm6vP0' ),
('col', 'col_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'ksXHrNHHHtY' ),
('col', 'col_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'bfTAqApCiIb' ),
('col', 'col_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'nm7Wxy7HTuy' ),
('col', 'col_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'o9EG0vv4RnO' ),
('col', 'col_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'rZLHuzg0Ayi' ),
('col', 'col_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'KrzsPmVyImR' ),
('col', 'col_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'Xyw52ZcXySb' ),
('col', 'col_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'tsSGKmerVFd', 'rkY5vfbP0SS' ),

/* Gentamicin - gen */
('gen', 'gen_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'IXtPp8evv23', 'X9MHIf0Wm6y' ),
('gen', 'gen_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'IXtPp8evv23', 'WeHrikdo7oo' ),
('gen', 'gen_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'IXtPp8evv23', 'hPnuIjnYi9C' ),
('gen', 'gen_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'IXtPp8evv23', 'ZFaU7TaQRZp' ),
('gen', 'gen_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'IXtPp8evv23', 'FbXf2g4uhos' ),
('gen', 'gen_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'IXtPp8evv23', 'iCcPaU1SKnO' ),
('gen', 'gen_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'IXtPp8evv23', 'eSNEiqOgZ03' ),
('gen', 'gen_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'IXtPp8evv23', 'Jy5IeplgNcs' ),
('gen', 'gen_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'IXtPp8evv23', 'VgMvVNtkUPv' ),
('gen', 'gen_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'IXtPp8evv23', 'Fh2PZJLtV3U' ),
('gen', 'gen_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'bOIEbuipQ0H' ),
('gen', 'gen_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'p3TAhB2UZiS' ),
('gen', 'gen_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'xvR3x8vLvRK' ),
('gen', 'gen_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'efl41btBUk9' ),
('gen', 'gen_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'ccisVG8SxHv' ),
('gen', 'gen_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'ZG21E9j1Bod' ),
('gen', 'gen_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'UdeU9gsKqI3' ),
('gen', 'gen_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'DI0hjMRK5Zh' ),
('gen', 'gen_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'ov2i9IayA9m' ),
('gen', 'gen_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'qX0d8PnsJvA' ),
('gen', 'gen_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'WkldENuMjt8' ),
('gen', 'gen_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'z9OAlfoLrhF' ),
('gen', 'gen_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'xhGDprZjJIy' ),
('gen', 'gen_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'KMjCdte3nlv' ),
('gen', 'gen_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'ameRGjO5AW3' ),
('gen', 'gen_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'LncgC06sQdO' ),
('gen', 'gen_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'LQQ8pGWtkiH' ),
('gen', 'gen_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'UXnM8Pm6vP0' ),
('gen', 'gen_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'ksXHrNHHHtY' ),
('gen', 'gen_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'bfTAqApCiIb' ),
('gen', 'gen_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'nm7Wxy7HTuy' ),
('gen', 'gen_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'o9EG0vv4RnO' ),
('gen', 'gen_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'rZLHuzg0Ayi' ),
('gen', 'gen_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'KrzsPmVyImR' ),
('gen', 'gen_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'Xyw52ZcXySb' ),
('gen', 'gen_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'IXtPp8evv23', 'rkY5vfbP0SS' ),

/* Imipenem - ipm */
('ipm', 'ipm_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'X9MHIf0Wm6y' ),
('ipm', 'ipm_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'WeHrikdo7oo' ),
('ipm', 'ipm_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'hPnuIjnYi9C' ),
('ipm', 'ipm_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'ZFaU7TaQRZp' ),
('ipm', 'ipm_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'FbXf2g4uhos' ),
('ipm', 'ipm_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'iCcPaU1SKnO' ),
('ipm', 'ipm_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'eSNEiqOgZ03' ),
('ipm', 'ipm_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'Jy5IeplgNcs' ),
('ipm', 'ipm_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'VgMvVNtkUPv' ),
('ipm', 'ipm_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'Fh2PZJLtV3U' ),
('ipm', 'ipm_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'bOIEbuipQ0H' ),
('ipm', 'ipm_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'p3TAhB2UZiS' ),
('ipm', 'ipm_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'xvR3x8vLvRK' ),
('ipm', 'ipm_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'efl41btBUk9' ),
('ipm', 'ipm_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'ccisVG8SxHv' ),
('ipm', 'ipm_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'ZG21E9j1Bod' ),
('ipm', 'ipm_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'UdeU9gsKqI3' ),
('ipm', 'ipm_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'DI0hjMRK5Zh' ),
('ipm', 'ipm_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'ov2i9IayA9m' ),
('ipm', 'ipm_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'qX0d8PnsJvA' ),
('ipm', 'ipm_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'WkldENuMjt8' ),
('ipm', 'ipm_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'z9OAlfoLrhF' ),
('ipm', 'ipm_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'xhGDprZjJIy' ),
('ipm', 'ipm_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'KMjCdte3nlv' ),
('ipm', 'ipm_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'ameRGjO5AW3' ),
('ipm', 'ipm_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'LncgC06sQdO' ),
('ipm', 'ipm_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'LQQ8pGWtkiH' ),
('ipm', 'ipm_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'UXnM8Pm6vP0' ),
('ipm', 'ipm_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'ksXHrNHHHtY' ),
('ipm', 'ipm_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'bfTAqApCiIb' ),
('ipm', 'ipm_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'nm7Wxy7HTuy' ),
('ipm', 'ipm_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'o9EG0vv4RnO' ),
('ipm', 'ipm_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'rZLHuzg0Ayi' ),
('ipm', 'ipm_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'KrzsPmVyImR' ),
('ipm', 'ipm_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'Xyw52ZcXySb' ),
('ipm', 'ipm_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'R1dNOZmUFBN', 'rkY5vfbP0SS' ),

/* Levofloxacin - lvx */
('lvx', 'lvx_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'X9MHIf0Wm6y' ),
('lvx', 'lvx_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'WeHrikdo7oo' ),
('lvx', 'lvx_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'hPnuIjnYi9C' ),
('lvx', 'lvx_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'ZFaU7TaQRZp' ),
('lvx', 'lvx_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'FbXf2g4uhos' ),
('lvx', 'lvx_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'iCcPaU1SKnO' ),
('lvx', 'lvx_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'eSNEiqOgZ03' ),
('lvx', 'lvx_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'Jy5IeplgNcs' ),
('lvx', 'lvx_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'VgMvVNtkUPv' ),
('lvx', 'lvx_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'Fh2PZJLtV3U' ),
('lvx', 'lvx_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'bOIEbuipQ0H' ),
('lvx', 'lvx_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'p3TAhB2UZiS' ),
('lvx', 'lvx_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'xvR3x8vLvRK' ),
('lvx', 'lvx_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'efl41btBUk9' ),
('lvx', 'lvx_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'ccisVG8SxHv' ),
('lvx', 'lvx_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'ZG21E9j1Bod' ),
('lvx', 'lvx_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'UdeU9gsKqI3' ),
('lvx', 'lvx_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'DI0hjMRK5Zh' ),
('lvx', 'lvx_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'ov2i9IayA9m' ),
('lvx', 'lvx_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'qX0d8PnsJvA' ),
('lvx', 'lvx_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'WkldENuMjt8' ),
('lvx', 'lvx_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'z9OAlfoLrhF' ),
('lvx', 'lvx_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'xhGDprZjJIy' ),
('lvx', 'lvx_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'KMjCdte3nlv' ),
('lvx', 'lvx_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'ameRGjO5AW3' ),
('lvx', 'lvx_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'LncgC06sQdO' ),
('lvx', 'lvx_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'LQQ8pGWtkiH' ),
('lvx', 'lvx_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'UXnM8Pm6vP0' ),
('lvx', 'lvx_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'ksXHrNHHHtY' ),
('lvx', 'lvx_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'bfTAqApCiIb' ),
('lvx', 'lvx_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'nm7Wxy7HTuy' ),
('lvx', 'lvx_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'o9EG0vv4RnO' ),
('lvx', 'lvx_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'rZLHuzg0Ayi' ),
('lvx', 'lvx_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'KrzsPmVyImR' ),
('lvx', 'lvx_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'Xyw52ZcXySb' ),
('lvx', 'lvx_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'dLxrh0TnVM9', 'rkY5vfbP0SS' ),

/* Meropenem - mem */
('mem', 'mem_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'FgIwttGZG84', 'X9MHIf0Wm6y' ),
('mem', 'mem_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'FgIwttGZG84', 'WeHrikdo7oo' ),
('mem', 'mem_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'FgIwttGZG84', 'hPnuIjnYi9C' ),
('mem', 'mem_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'FgIwttGZG84', 'ZFaU7TaQRZp' ),
('mem', 'mem_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'FgIwttGZG84', 'FbXf2g4uhos' ),
('mem', 'mem_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'FgIwttGZG84', 'iCcPaU1SKnO' ),
('mem', 'mem_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'FgIwttGZG84', 'eSNEiqOgZ03' ),
('mem', 'mem_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'FgIwttGZG84', 'Jy5IeplgNcs' ),
('mem', 'mem_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'FgIwttGZG84', 'VgMvVNtkUPv' ),
('mem', 'mem_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'FgIwttGZG84', 'Fh2PZJLtV3U' ),
('mem', 'mem_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'bOIEbuipQ0H' ),
('mem', 'mem_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'p3TAhB2UZiS' ),
('mem', 'mem_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'xvR3x8vLvRK' ),
('mem', 'mem_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'efl41btBUk9' ),
('mem', 'mem_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'ccisVG8SxHv' ),
('mem', 'mem_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'ZG21E9j1Bod' ),
('mem', 'mem_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'UdeU9gsKqI3' ),
('mem', 'mem_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'DI0hjMRK5Zh' ),
('mem', 'mem_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'ov2i9IayA9m' ),
('mem', 'mem_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'qX0d8PnsJvA' ),
('mem', 'mem_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'WkldENuMjt8' ),
('mem', 'mem_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'z9OAlfoLrhF' ),
('mem', 'mem_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'xhGDprZjJIy' ),
('mem', 'mem_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'KMjCdte3nlv' ),
('mem', 'mem_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'ameRGjO5AW3' ),
('mem', 'mem_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'LncgC06sQdO' ),
('mem', 'mem_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'LQQ8pGWtkiH' ),
('mem', 'mem_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'UXnM8Pm6vP0' ),
('mem', 'mem_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'ksXHrNHHHtY' ),
('mem', 'mem_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'bfTAqApCiIb' ),
('mem', 'mem_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'nm7Wxy7HTuy' ),
('mem', 'mem_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'o9EG0vv4RnO' ),
('mem', 'mem_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'rZLHuzg0Ayi' ),
('mem', 'mem_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'KrzsPmVyImR' ),
('mem', 'mem_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'Xyw52ZcXySb' ),
('mem', 'mem_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'FgIwttGZG84', 'rkY5vfbP0SS' ),

/* Oxacillin - oxa */
('oxa', 'oxa_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'yBkiklHuwne', 'X9MHIf0Wm6y' ),
('oxa', 'oxa_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'yBkiklHuwne', 'WeHrikdo7oo' ),
('oxa', 'oxa_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'yBkiklHuwne', 'hPnuIjnYi9C' ),
('oxa', 'oxa_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'yBkiklHuwne', 'ZFaU7TaQRZp' ),
('oxa', 'oxa_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'yBkiklHuwne', 'FbXf2g4uhos' ),
('oxa', 'oxa_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'yBkiklHuwne', 'iCcPaU1SKnO' ),
('oxa', 'oxa_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'yBkiklHuwne', 'eSNEiqOgZ03' ),
('oxa', 'oxa_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'yBkiklHuwne', 'Jy5IeplgNcs' ),
('oxa', 'oxa_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'yBkiklHuwne', 'VgMvVNtkUPv' ),
('oxa', 'oxa_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'yBkiklHuwne', 'Fh2PZJLtV3U' ),
('oxa', 'oxa_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'bOIEbuipQ0H' ),
('oxa', 'oxa_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'p3TAhB2UZiS' ),
('oxa', 'oxa_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'xvR3x8vLvRK' ),
('oxa', 'oxa_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'efl41btBUk9' ),
('oxa', 'oxa_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'ccisVG8SxHv' ),
('oxa', 'oxa_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'ZG21E9j1Bod' ),
('oxa', 'oxa_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'UdeU9gsKqI3' ),
('oxa', 'oxa_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'DI0hjMRK5Zh' ),
('oxa', 'oxa_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'ov2i9IayA9m' ),
('oxa', 'oxa_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'qX0d8PnsJvA' ),
('oxa', 'oxa_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'WkldENuMjt8' ),
('oxa', 'oxa_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'z9OAlfoLrhF' ),
('oxa', 'oxa_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'xhGDprZjJIy' ),
('oxa', 'oxa_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'KMjCdte3nlv' ),
('oxa', 'oxa_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'ameRGjO5AW3' ),
('oxa', 'oxa_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'LncgC06sQdO' ),
('oxa', 'oxa_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'LQQ8pGWtkiH' ),
('oxa', 'oxa_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'UXnM8Pm6vP0' ),
('oxa', 'oxa_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'ksXHrNHHHtY' ),
('oxa', 'oxa_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'bfTAqApCiIb' ),
('oxa', 'oxa_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'nm7Wxy7HTuy' ),
('oxa', 'oxa_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'o9EG0vv4RnO' ),
('oxa', 'oxa_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'rZLHuzg0Ayi' ),
('oxa', 'oxa_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'KrzsPmVyImR' ),
('oxa', 'oxa_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'Xyw52ZcXySb' ),
('oxa', 'oxa_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'yBkiklHuwne', 'rkY5vfbP0SS' ),

/* Penicillin G - pen */
('pen', 'pen_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'X9MHIf0Wm6y' ),
('pen', 'pen_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'WeHrikdo7oo' ),
('pen', 'pen_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'hPnuIjnYi9C' ),
('pen', 'pen_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'ZFaU7TaQRZp' ),
('pen', 'pen_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'FbXf2g4uhos' ),
('pen', 'pen_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'iCcPaU1SKnO' ),
('pen', 'pen_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'eSNEiqOgZ03' ),
('pen', 'pen_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'Jy5IeplgNcs' ),
('pen', 'pen_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'VgMvVNtkUPv' ),
('pen', 'pen_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'Fh2PZJLtV3U' ),
('pen', 'pen_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'bOIEbuipQ0H' ),
('pen', 'pen_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'p3TAhB2UZiS' ),
('pen', 'pen_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'xvR3x8vLvRK' ),
('pen', 'pen_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'efl41btBUk9' ),
('pen', 'pen_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'ccisVG8SxHv' ),
('pen', 'pen_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'ZG21E9j1Bod' ),
('pen', 'pen_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'UdeU9gsKqI3' ),
('pen', 'pen_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'DI0hjMRK5Zh' ),
('pen', 'pen_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'ov2i9IayA9m' ),
('pen', 'pen_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'qX0d8PnsJvA' ),
('pen', 'pen_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'WkldENuMjt8' ),
('pen', 'pen_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'z9OAlfoLrhF' ),
('pen', 'pen_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'xhGDprZjJIy' ),
('pen', 'pen_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'KMjCdte3nlv' ),
('pen', 'pen_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'ameRGjO5AW3' ),
('pen', 'pen_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'LncgC06sQdO' ),
('pen', 'pen_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'LQQ8pGWtkiH' ),
('pen', 'pen_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'UXnM8Pm6vP0' ),
('pen', 'pen_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'ksXHrNHHHtY' ),
('pen', 'pen_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'bfTAqApCiIb' ),
('pen', 'pen_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'nm7Wxy7HTuy' ),
('pen', 'pen_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'o9EG0vv4RnO' ),
('pen', 'pen_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'rZLHuzg0Ayi' ),
('pen', 'pen_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'KrzsPmVyImR' ),
('pen', 'pen_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'Xyw52ZcXySb' ),
('pen', 'pen_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'uEqTLSvaBFd', 'rkY5vfbP0SS' ),

/* Vancomycin - van */
('van', 'van_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'X9MHIf0Wm6y' ),
('van', 'van_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'WeHrikdo7oo' ),
('van', 'van_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'hPnuIjnYi9C' ),
('van', 'van_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'ZFaU7TaQRZp' ),
('van', 'van_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'FbXf2g4uhos' ),
('van', 'van_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'iCcPaU1SKnO' ),
('van', 'van_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'eSNEiqOgZ03' ),
('van', 'van_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'Jy5IeplgNcs' ),
('van', 'van_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'VgMvVNtkUPv' ),
('van', 'van_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'Fh2PZJLtV3U' ),
('van', 'van_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'bOIEbuipQ0H' ),
('van', 'van_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'p3TAhB2UZiS' ),
('van', 'van_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'xvR3x8vLvRK' ),
('van', 'van_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'efl41btBUk9' ),
('van', 'van_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'ccisVG8SxHv' ),
('van', 'van_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'ZG21E9j1Bod' ),
('van', 'van_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'UdeU9gsKqI3' ),
('van', 'van_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'DI0hjMRK5Zh' ),
('van', 'van_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'ov2i9IayA9m' ),
('van', 'van_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'qX0d8PnsJvA' ),
('van', 'van_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'WkldENuMjt8' ),
('van', 'van_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'z9OAlfoLrhF' ),
('van', 'van_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'xhGDprZjJIy' ),
('van', 'van_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'KMjCdte3nlv' ),
('van', 'van_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'ameRGjO5AW3' ),
('van', 'van_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'LncgC06sQdO' ),
('van', 'van_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'LQQ8pGWtkiH' ),
('van', 'van_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'UXnM8Pm6vP0' ),
('van', 'van_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'ksXHrNHHHtY' ),
('van', 'van_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'bfTAqApCiIb' ),
('van', 'van_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'nm7Wxy7HTuy' ),
('van', 'van_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'o9EG0vv4RnO' ),
('van', 'van_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'rZLHuzg0Ayi' ),
('van', 'van_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'KrzsPmVyImR' ),
('van', 'van_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'Xyw52ZcXySb' ),
('van', 'van_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'dXRwLsPJbzE', 'rkY5vfbP0SS' ),

/* Augmentin */
/*
('', '', 'kpn_r', 0, '', 'quMWqLxzcfO', '', '' ),
('', '', 'kpn_i', 0, '', 'quMWqLxzcfO', '', '' ),
('', '', 'kpn_s', 0, '', 'quMWqLxzcfO', '', '' ),*/

/* Chloramphenicol - chl */
('chl', 'chl_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'X9MHIf0Wm6y' ),
('chl', 'chl_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'WeHrikdo7oo' ),
('chl', 'chl_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'hPnuIjnYi9C' ),
('chl', 'chl_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'ZFaU7TaQRZp' ),
('chl', 'chl_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'FbXf2g4uhos' ),
('chl', 'chl_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'iCcPaU1SKnO' ),
('chl', 'chl_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'eSNEiqOgZ03' ),
('chl', 'chl_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'Jy5IeplgNcs' ),
('chl', 'chl_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'VgMvVNtkUPv' ),
('chl', 'chl_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'Fh2PZJLtV3U' ),
('chl', 'chl_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'bOIEbuipQ0H' ),
('chl', 'chl_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'p3TAhB2UZiS' ),
('chl', 'chl_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'xvR3x8vLvRK' ),
('chl', 'chl_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'efl41btBUk9' ),
('chl', 'chl_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'ccisVG8SxHv' ),
('chl', 'chl_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'ZG21E9j1Bod' ),
('chl', 'chl_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'UdeU9gsKqI3' ),
('chl', 'chl_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'DI0hjMRK5Zh' ),
('chl', 'chl_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'ov2i9IayA9m' ),
('chl', 'chl_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'qX0d8PnsJvA' ),
('chl', 'chl_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'WkldENuMjt8' ),
('chl', 'chl_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'z9OAlfoLrhF' ),
('chl', 'chl_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'xhGDprZjJIy' ),
('chl', 'chl_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'KMjCdte3nlv' ),
('chl', 'chl_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'ameRGjO5AW3' ),
('chl', 'chl_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'LncgC06sQdO' ),
('chl', 'chl_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'LQQ8pGWtkiH' ),
('chl', 'chl_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'UXnM8Pm6vP0' ),
('chl', 'chl_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'ksXHrNHHHtY' ),
('chl', 'chl_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'bfTAqApCiIb' ),
('chl', 'chl_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'nm7Wxy7HTuy' ),
('chl', 'chl_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'o9EG0vv4RnO' ),
('chl', 'chl_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'rZLHuzg0Ayi' ),
('chl', 'chl_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'KrzsPmVyImR' ),
('chl', 'chl_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'Xyw52ZcXySb' ),
('chl', 'chl_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'pr8BhPFhXRF', 'rkY5vfbP0SS' ),

/* Clindamycin - cli */
('cli', 'cli_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'X9MHIf0Wm6y' ),
('cli', 'cli_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'WeHrikdo7oo' ),
('cli', 'cli_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'hPnuIjnYi9C' ),
('cli', 'cli_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'ZFaU7TaQRZp' ),
('cli', 'cli_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'FbXf2g4uhos' ),
('cli', 'cli_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'iCcPaU1SKnO' ),
('cli', 'cli_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'eSNEiqOgZ03' ),
('cli', 'cli_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'Jy5IeplgNcs' ),
('cli', 'cli_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'VgMvVNtkUPv' ),
('cli', 'cli_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'Fh2PZJLtV3U' ),
('cli', 'cli_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'bOIEbuipQ0H' ),
('cli', 'cli_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'p3TAhB2UZiS' ),
('cli', 'cli_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'xvR3x8vLvRK' ),
('cli', 'cli_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'efl41btBUk9' ),
('cli', 'cli_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'ccisVG8SxHv' ),
('cli', 'cli_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'ZG21E9j1Bod' ),
('cli', 'cli_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'UdeU9gsKqI3' ),
('cli', 'cli_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'DI0hjMRK5Zh' ),
('cli', 'cli_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'ov2i9IayA9m' ),
('cli', 'cli_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'qX0d8PnsJvA' ),
('cli', 'cli_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'WkldENuMjt8' ),
('cli', 'cli_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'z9OAlfoLrhF' ),
('cli', 'cli_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'xhGDprZjJIy' ),
('cli', 'cli_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'KMjCdte3nlv' ),
('cli', 'cli_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'ameRGjO5AW3' ),
('cli', 'cli_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'LncgC06sQdO' ),
('cli', 'cli_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'LQQ8pGWtkiH' ),
('cli', 'cli_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'UXnM8Pm6vP0' ),
('cli', 'cli_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'ksXHrNHHHtY' ),
('cli', 'cli_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'bfTAqApCiIb' ),
('cli', 'cli_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'nm7Wxy7HTuy' ),
('cli', 'cli_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'o9EG0vv4RnO' ),
('cli', 'cli_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'rZLHuzg0Ayi' ),
('cli', 'cli_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'KrzsPmVyImR' ),
('cli', 'cli_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'Xyw52ZcXySb' ),
('cli', 'cli_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'SWGZmBEEhT6', 'rkY5vfbP0SS' ),

/* Erythromycin - ery */
('ery', 'ery_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'QvgZSManeJs', 'X9MHIf0Wm6y' ),
('ery', 'ery_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'QvgZSManeJs', 'WeHrikdo7oo' ),
('ery', 'ery_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'QvgZSManeJs', 'hPnuIjnYi9C' ),
('ery', 'ery_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'QvgZSManeJs', 'ZFaU7TaQRZp' ),
('ery', 'ery_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'QvgZSManeJs', 'FbXf2g4uhos' ),
('ery', 'ery_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'QvgZSManeJs', 'iCcPaU1SKnO' ),
('ery', 'ery_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'QvgZSManeJs', 'eSNEiqOgZ03' ),
('ery', 'ery_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'QvgZSManeJs', 'Jy5IeplgNcs' ),
('ery', 'ery_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'QvgZSManeJs', 'VgMvVNtkUPv' ),
('ery', 'ery_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'QvgZSManeJs', 'Fh2PZJLtV3U' ),
('ery', 'ery_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'bOIEbuipQ0H' ),
('ery', 'ery_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'p3TAhB2UZiS' ),
('ery', 'ery_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'xvR3x8vLvRK' ),
('ery', 'ery_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'efl41btBUk9' ),
('ery', 'ery_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'ccisVG8SxHv' ),
('ery', 'ery_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'ZG21E9j1Bod' ),
('ery', 'ery_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'UdeU9gsKqI3' ),
('ery', 'ery_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'DI0hjMRK5Zh' ),
('ery', 'ery_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'ov2i9IayA9m' ),
('ery', 'ery_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'qX0d8PnsJvA' ),
('ery', 'ery_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'WkldENuMjt8' ),
('ery', 'ery_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'z9OAlfoLrhF' ),
('ery', 'ery_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'xhGDprZjJIy' ),
('ery', 'ery_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'KMjCdte3nlv' ),
('ery', 'ery_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'ameRGjO5AW3' ),
('ery', 'ery_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'LncgC06sQdO' ),
('ery', 'ery_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'LQQ8pGWtkiH' ),
('ery', 'ery_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'UXnM8Pm6vP0' ),
('ery', 'ery_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'ksXHrNHHHtY' ),
('ery', 'ery_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'bfTAqApCiIb' ),
('ery', 'ery_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'nm7Wxy7HTuy' ),
('ery', 'ery_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'o9EG0vv4RnO' ),
('ery', 'ery_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'rZLHuzg0Ayi' ),
('ery', 'ery_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'KrzsPmVyImR' ),
('ery', 'ery_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'Xyw52ZcXySb' ),
('ery', 'ery_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'QvgZSManeJs', 'rkY5vfbP0SS' ),


/* Nalidixic acid - nal */
('nal', 'nal_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'c8iFsTL0172', 'X9MHIf0Wm6y' ),
('nal', 'nal_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'c8iFsTL0172', 'WeHrikdo7oo' ),
('nal', 'nal_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'c8iFsTL0172', 'hPnuIjnYi9C' ),
('nal', 'nal_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'c8iFsTL0172', 'ZFaU7TaQRZp' ),
('nal', 'nal_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'c8iFsTL0172', 'FbXf2g4uhos' ),
('nal', 'nal_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'c8iFsTL0172', 'iCcPaU1SKnO' ),
('nal', 'nal_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'c8iFsTL0172', 'eSNEiqOgZ03' ),
('nal', 'nal_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'c8iFsTL0172', 'Jy5IeplgNcs' ),
('nal', 'nal_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'c8iFsTL0172', 'VgMvVNtkUPv' ),
('nal', 'nal_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'c8iFsTL0172', 'Fh2PZJLtV3U' ),
('nal', 'nal_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'bOIEbuipQ0H' ),
('nal', 'nal_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'p3TAhB2UZiS' ),
('nal', 'nal_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'xvR3x8vLvRK' ),
('nal', 'nal_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'efl41btBUk9' ),
('nal', 'nal_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'ccisVG8SxHv' ),
('nal', 'nal_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'ZG21E9j1Bod' ),
('nal', 'nal_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'UdeU9gsKqI3' ),
('nal', 'nal_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'DI0hjMRK5Zh' ),
('nal', 'nal_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'ov2i9IayA9m' ),
('nal', 'nal_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'qX0d8PnsJvA' ),
('nal', 'nal_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'WkldENuMjt8' ),
('nal', 'nal_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'z9OAlfoLrhF' ),
('nal', 'nal_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'xhGDprZjJIy' ),
('nal', 'nal_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'KMjCdte3nlv' ),
('nal', 'nal_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'ameRGjO5AW3' ),
('nal', 'nal_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'LncgC06sQdO' ),
('nal', 'nal_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'LQQ8pGWtkiH' ),
('nal', 'nal_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'UXnM8Pm6vP0' ),
('nal', 'nal_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'ksXHrNHHHtY' ),
('nal', 'nal_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'bfTAqApCiIb' ),
('nal', 'nal_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'nm7Wxy7HTuy' ),
('nal', 'nal_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'o9EG0vv4RnO' ),
('nal', 'nal_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'rZLHuzg0Ayi' ),
('nal', 'nal_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'KrzsPmVyImR' ),
('nal', 'nal_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'Xyw52ZcXySb' ),
('nal', 'nal_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'c8iFsTL0172', 'rkY5vfbP0SS' ),

/* Nitrofurantoin - nit */
('nit', 'nit_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'X9MHIf0Wm6y' ),
('nit', 'nit_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'WeHrikdo7oo' ),
('nit', 'nit_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'hPnuIjnYi9C' ),
('nit', 'nit_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'ZFaU7TaQRZp' ),
('nit', 'nit_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'FbXf2g4uhos' ),
('nit', 'nit_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'iCcPaU1SKnO' ),
('nit', 'nit_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'eSNEiqOgZ03' ),
('nit', 'nit_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'Jy5IeplgNcs' ),
('nit', 'nit_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'VgMvVNtkUPv' ),
('nit', 'nit_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'Fh2PZJLtV3U' ),
('nit', 'nit_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'bOIEbuipQ0H' ),
('nit', 'nit_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'p3TAhB2UZiS' ),
('nit', 'nit_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'xvR3x8vLvRK' ),
('nit', 'nit_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'efl41btBUk9' ),
('nit', 'nit_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'ccisVG8SxHv' ),
('nit', 'nit_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'ZG21E9j1Bod' ),
('nit', 'nit_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'UdeU9gsKqI3' ),
('nit', 'nit_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'DI0hjMRK5Zh' ),
('nit', 'nit_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'ov2i9IayA9m' ),
('nit', 'nit_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'qX0d8PnsJvA' ),
('nit', 'nit_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'WkldENuMjt8' ),
('nit', 'nit_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'z9OAlfoLrhF' ),
('nit', 'nit_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'xhGDprZjJIy' ),
('nit', 'nit_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'KMjCdte3nlv' ),
('nit', 'nit_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'ameRGjO5AW3' ),
('nit', 'nit_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'LncgC06sQdO' ),
('nit', 'nit_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'LQQ8pGWtkiH' ),
('nit', 'nit_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'UXnM8Pm6vP0' ),
('nit', 'nit_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'ksXHrNHHHtY' ),
('nit', 'nit_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'bfTAqApCiIb' ),
('nit', 'nit_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'nm7Wxy7HTuy' ),
('nit', 'nit_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'o9EG0vv4RnO' ),
('nit', 'nit_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'rZLHuzg0Ayi' ),
('nit', 'nit_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'KrzsPmVyImR' ),
('nit', 'nit_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'Xyw52ZcXySb' ),
('nit', 'nit_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'FGer9X7aDSk', 'rkY5vfbP0SS' ),

/* Piperacillin - pip */
('pip', 'pip_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'X9MHIf0Wm6y' ),
('pip', 'pip_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'WeHrikdo7oo' ),
('pip', 'pip_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'hPnuIjnYi9C' ),
('pip', 'pip_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'ZFaU7TaQRZp' ),
('pip', 'pip_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'FbXf2g4uhos' ),
('pip', 'pip_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'iCcPaU1SKnO' ),
('pip', 'pip_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'eSNEiqOgZ03' ),
('pip', 'pip_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'Jy5IeplgNcs' ),
('pip', 'pip_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'VgMvVNtkUPv' ),
('pip', 'pip_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'Fh2PZJLtV3U' ),
('pip', 'pip_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'bOIEbuipQ0H' ),
('pip', 'pip_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'p3TAhB2UZiS' ),
('pip', 'pip_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'xvR3x8vLvRK' ),
('pip', 'pip_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'efl41btBUk9' ),
('pip', 'pip_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'ccisVG8SxHv' ),
('pip', 'pip_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'ZG21E9j1Bod' ),
('pip', 'pip_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'UdeU9gsKqI3' ),
('pip', 'pip_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'DI0hjMRK5Zh' ),
('pip', 'pip_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'ov2i9IayA9m' ),
('pip', 'pip_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'qX0d8PnsJvA' ),
('pip', 'pip_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'WkldENuMjt8' ),
('pip', 'pip_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'z9OAlfoLrhF' ),
('pip', 'pip_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'xhGDprZjJIy' ),
('pip', 'pip_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'KMjCdte3nlv' ),
('pip', 'pip_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'ameRGjO5AW3' ),
('pip', 'pip_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'LncgC06sQdO' ),
('pip', 'pip_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'LQQ8pGWtkiH' ),
('pip', 'pip_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'UXnM8Pm6vP0' ),
('pip', 'pip_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'ksXHrNHHHtY' ),
('pip', 'pip_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'bfTAqApCiIb' ),
('pip', 'pip_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'nm7Wxy7HTuy' ),
('pip', 'pip_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'o9EG0vv4RnO' ),
('pip', 'pip_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'rZLHuzg0Ayi' ),
('pip', 'pip_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'KrzsPmVyImR' ),
('pip', 'pip_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'Xyw52ZcXySb' ),
('pip', 'pip_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'HYgmHZAlikA', 'rkY5vfbP0SS' ),

/* Piperacillin/Tazobactam */
/*
('', '', 'kpn_r', 0, '', 'quMWqLxzcfO', '', '' ),
('', '', 'kpn_i', 0, '', 'quMWqLxzcfO', '', '' ),
('', '', 'kpn_s', 0, '', 'quMWqLxzcfO', '', '' ),*/

/* Tetracycline - tcy */
('tcy', 'tcy_kpn_r', 'kpn_r', 0 , '', 'quMWqLxzcfO', 'adziW8wj1ke', 'X9MHIf0Wm6y' ),
('tcy', 'tcy_kpn_i', 'kpn_i', 1 , '', 'quMWqLxzcfO', 'adziW8wj1ke', 'WeHrikdo7oo' ),
('tcy', 'tcy_kpn_s', 'kpn_s', 2 , '', 'quMWqLxzcfO', 'adziW8wj1ke', 'hPnuIjnYi9C' ),
('tcy', 'tcy_eco_r', 'eco_r', 3 , '', 'quMWqLxzcfO', 'adziW8wj1ke', 'ZFaU7TaQRZp' ),
('tcy', 'tcy_eco_i', 'eco_i', 4 , '', 'quMWqLxzcfO', 'adziW8wj1ke', 'FbXf2g4uhos' ),
('tcy', 'tcy_eco_s', 'eco_s', 5 , '', 'quMWqLxzcfO', 'adziW8wj1ke', 'iCcPaU1SKnO' ),
('tcy', 'tcy_sal_r', 'sal_r', 6 , '', 'quMWqLxzcfO', 'adziW8wj1ke', 'eSNEiqOgZ03' ),
('tcy', 'tcy_sal_i', 'sal_i', 7 , '', 'quMWqLxzcfO', 'adziW8wj1ke', 'Jy5IeplgNcs' ),
('tcy', 'tcy_sal_s', 'sal_s', 8 , '', 'quMWqLxzcfO', 'adziW8wj1ke', 'VgMvVNtkUPv' ),
('tcy', 'tcy_shi_r', 'shi_r', 9 , '', 'quMWqLxzcfO', 'adziW8wj1ke', 'Fh2PZJLtV3U' ),
('tcy', 'tcy_shi_i', 'shi_i', 10, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'bOIEbuipQ0H' ),
('tcy', 'tcy_shi_s', 'shi_s', 11, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'p3TAhB2UZiS' ),
('tcy', 'tcy_ngo_r', 'ngo_r', 12, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'xvR3x8vLvRK' ),
('tcy', 'tcy_ngo_i', 'ngo_i', 13, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'efl41btBUk9' ),
('tcy', 'tcy_ngo_s', 'ngo_s', 14, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'ccisVG8SxHv' ),
('tcy', 'tcy_sau_r', 'sau_r', 15, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'ZG21E9j1Bod' ),
('tcy', 'tcy_sau_i', 'sau_i', 16, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'UdeU9gsKqI3' ),
('tcy', 'tcy_sau_s', 'sau_s', 17, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'DI0hjMRK5Zh' ),
('tcy', 'tcy_spn_r', 'spn_r', 18, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'ov2i9IayA9m' ),
('tcy', 'tcy_spn_i', 'spn_i', 19, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'qX0d8PnsJvA' ),
('tcy', 'tcy_spn_s', 'spn_s', 20, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'WkldENuMjt8' ),
('tcy', 'tcy_aba_r', 'aba_r', 21, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'z9OAlfoLrhF' ),
('tcy', 'tcy_aba_i', 'aba_i', 22, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'xhGDprZjJIy' ),
('tcy', 'tcy_aba_s', 'aba_s', 23, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'KMjCdte3nlv' ),
('tcy', 'tcy_vic_r', 'vic_r', 24, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'ameRGjO5AW3' ),
('tcy', 'tcy_vic_i', 'vic_i', 25, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'LncgC06sQdO' ),
('tcy', 'tcy_vic_s', 'vic_s', 26, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'LQQ8pGWtkiH' ),
('tcy', 'tcy_ent_r', 'ent_r', 27, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'UXnM8Pm6vP0' ),
('tcy', 'tcy_ent_i', 'ent_i', 28, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'ksXHrNHHHtY' ),
('tcy', 'tcy_ent_s', 'ent_s', 29, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'bfTAqApCiIb' ),
('tcy', 'tcy_hin_r', 'hin_r', 30, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'nm7Wxy7HTuy' ),
('tcy', 'tcy_hin_i', 'hin_i', 31, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'o9EG0vv4RnO' ),
('tcy', 'tcy_hin_s', 'hin_s', 32, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'rZLHuzg0Ayi' ),
('tcy', 'tcy_nme_r', 'nme_r', 34, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'KrzsPmVyImR' ),
('tcy', 'tcy_nme_i', 'nme_i', 35, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'Xyw52ZcXySb' ),
('tcy', 'tcy_nme_s', 'nme_s', 36, '', 'quMWqLxzcfO', 'adziW8wj1ke', 'rkY5vfbP0SS' );
